[workspace]
resolver = "2"
members = ["crates/clew"]

[workspace.package]
version = "0.2.5"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ed25519-dalek = "2.2"
hex = "0.4"
prost = "0.14"
crossbeam-channel = "0.5"
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
syn = { version = "2.0", features = ["full", "visit"] }
tempfile = "3.23"
thiserror = "2.0"
uuid = { version = "1.19", features = ["v4", "serde"] }
unicode-normalization = "0.1"
walkdir = "2.5"

[profile.release]
strip = "symbols"
